"""create all tables

Revision ID: 7861cf029bb8
Revises: c79b6bd41259
Create Date: 2026-04-03 11:18:07.330015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7861cf029bb8'
down_revision: Union[str, None] = 'c79b6bd41259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affiliate_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('location_type', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('affiliate_index')
    )
    op.create_table('branch_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=50), nullable=False),
    sa.Column('raw_count', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_keywords_branch_id'), 'branch_keywords', ['branch_id'], unique=False)
    op.create_index('uq_branch_keywords_composite', 'branch_keywords', ['branch_id', 'keyword'], unique=True)
    op.create_table('branch_reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_name', sa.Text(), nullable=False),
    sa.Column('affiliate_name', sa.Text(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_viewed', sa.Boolean(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_storage_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_reports_branch_id'), 'branch_reports', ['branch_id'], unique=False)
    op.create_index('uq_branch_reports_composite', 'branch_reports', ['branch_id', 'period_start', 'period_end'], unique=True)
    op.create_table('branch_reviews',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('reservation_id', sa.String(length=50), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('rating_service', sa.Float(), nullable=True),
    sa.Column('rating_car', sa.Float(), nullable=True),
    sa.Column('rating_convenience', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('car_model', sa.String(length=100), nullable=True),
    sa.Column('rent_type', sa.String(length=20), nullable=True),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rental_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_branch_reviews_rental_date', 'branch_reviews', ['rental_date'], unique=False)
    op.create_index('idx_branch_reviews_return_date', 'branch_reviews', ['return_date'], unique=False)
    op.create_index(op.f('ix_branch_reviews_branch_id'), 'branch_reviews', ['branch_id'], unique=False)
    op.create_index('uq_branch_reviews_review_id', 'branch_reviews', ['review_id'], unique=True)
    op.create_table('branch_scheduler_settings',
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('summary_cycle', sa.String(length=20), nullable=False),
    sa.Column('min_reviews', sa.Integer(), nullable=False),
    sa.Column('auto_approve', sa.Boolean(), nullable=False),
    sa.Column('last_summary_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_summary_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('branch_id')
    )
    op.create_table('branch_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keyword_1', sa.String(length=50), nullable=True),
    sa.Column('keyword_2', sa.String(length=50), nullable=True),
    sa.Column('keyword_3', sa.String(length=50), nullable=True),
    sa.Column('summary_all', sa.Text(), nullable=True),
    sa.Column('summary_1y', sa.Text(), nullable=True),
    sa.Column('summary_6m', sa.Text(), nullable=True),
    sa.Column('summary_3m', sa.Text(), nullable=True),
    sa.Column('summary_1m', sa.Text(), nullable=True),
    sa.Column('pending_summaries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_report_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_summaries_branch_id'), 'branch_summaries', ['branch_id'], unique=True)
    op.create_table('branch_summaries_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('summary_all', sa.Text(), nullable=True),
    sa.Column('summary_1y', sa.Text(), nullable=True),
    sa.Column('summary_6m', sa.Text(), nullable=True),
    sa.Column('summary_3m', sa.Text(), nullable=True),
    sa.Column('summary_1m', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('generated_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_summaries_history_branch_id'), 'branch_summaries_history', ['branch_id'], unique=False)
    op.create_table('car_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(length=50), nullable=True),
    sa.Column('transmission', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id')
    )
    op.create_table('car_models_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('manufacturer', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_car_models_master_model_name', 'car_models_master', ['model_name'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_rating_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('avg_rating_service', sa.Float(), nullable=True),
    sa.Column('avg_rating_car', sa.Float(), nullable=True),
    sa.Column('avg_rating_convenience', sa.Float(), nullable=True),
    sa.Column('avg_rating_total', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_rating_stats_branch_id'), 'monthly_rating_stats', ['branch_id'], unique=False)
    op.create_index('uq_monthly_rating_stats_composite', 'monthly_rating_stats', ['branch_id', 'period'], unique=True)
    op.create_table('monthly_sentiment_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=False),
    sa.Column('negative_count', sa.Integer(), nullable=False),
    sa.Column('neutral_count', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_sentiment_stats_branch_id'), 'monthly_sentiment_stats', ['branch_id'], unique=False)
    op.create_index('uq_monthly_sentiment_stats_composite', 'monthly_sentiment_stats', ['branch_id', 'period'], unique=True)
    op.create_table('prompt_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('branch_type', sa.String(length=20), nullable=True),
    sa.Column('analysis_perspective', sa.String(length=30), nullable=False),
    sa.Column('tone', sa.String(length=30), nullable=False),
    sa.Column('detail_level', sa.String(length=20), nullable=False),
    sa.Column('focus_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_instruction', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('summary_max_length', sa.Integer(), nullable=False),
    sa.Column('eval_max_length', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_jobs',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.String(length=50), nullable=False),
    sa.Column('group_name', sa.String(length=200), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schedule_groups_workflow', 'schedule_groups', ['workflow_id'], unique=False)
    op.create_table('sync_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('lock_acquired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sync_type')
    )
    op.create_table('branch_car_models',
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('car_model_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['car_model_id'], ['car_models_master.id'], ),
    sa.PrimaryKeyConstraint('branch_id', 'car_model_id')
    )
    op.create_table('scheduler_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.String(length=50), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['schedule_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scheduler_targets_group', 'scheduler_targets', ['group_id'], unique=False)
    op.create_index('idx_scheduler_targets_workflow', 'scheduler_targets', ['workflow_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('sentiment', sa.String(length=10), nullable=False),
    sa.Column('tag_type', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('sentiment_type', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_tags_name', 'tags', ['name'], unique=True)
    op.create_table('branch_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=False),
    sa.Column('negative_count', sa.Integer(), nullable=False),
    sa.Column('neutral_count', sa.Integer(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_branch_tags_composite', 'branch_tags', ['branch_id', 'tag_id', 'period_type'], unique=True)
    op.create_table('keyword_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword')
    )
    op.create_table('monthly_car_model_tag_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('car_model_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=False),
    sa.Column('negative_count', sa.Integer(), nullable=False),
    sa.Column('neutral_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['car_model_id'], ['car_models_master.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_car_model_tag_stats_car_model_id'), 'monthly_car_model_tag_stats', ['car_model_id'], unique=False)
    op.create_index('uq_monthly_car_model_tag_stats_composite', 'monthly_car_model_tag_stats', ['car_model_id', 'period', 'tag_id'], unique=True)
    op.create_table('monthly_tag_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=False),
    sa.Column('negative_count', sa.Integer(), nullable=False),
    sa.Column('neutral_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_tag_stats_branch_id'), 'monthly_tag_stats', ['branch_id'], unique=False)
    op.create_index('uq_monthly_tag_stats_composite', 'monthly_tag_stats', ['branch_id', 'period', 'tag_id'], unique=True)
    op.create_table('review_tag_mappings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('matched_keyword', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_tag_mappings_review_id'), 'review_tag_mappings', ['review_id'], unique=False)
    op.create_index('uq_review_tag_mappings_composite', 'review_tag_mappings', ['review_id', 'tag_id', 'sentiment'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_review_tag_mappings_composite', table_name='review_tag_mappings')
    op.drop_index(op.f('ix_review_tag_mappings_review_id'), table_name='review_tag_mappings')
    op.drop_table('review_tag_mappings')
    op.drop_index('uq_monthly_tag_stats_composite', table_name='monthly_tag_stats')
    op.drop_index(op.f('ix_monthly_tag_stats_branch_id'), table_name='monthly_tag_stats')
    op.drop_table('monthly_tag_stats')
    op.drop_index('uq_monthly_car_model_tag_stats_composite', table_name='monthly_car_model_tag_stats')
    op.drop_index(op.f('ix_monthly_car_model_tag_stats_car_model_id'), table_name='monthly_car_model_tag_stats')
    op.drop_table('monthly_car_model_tag_stats')
    op.drop_table('keyword_mappings')
    op.drop_index('uq_branch_tags_composite', table_name='branch_tags')
    op.drop_table('branch_tags')
    op.drop_index('uq_tags_name', table_name='tags')
    op.drop_table('tags')
    op.drop_index('idx_scheduler_targets_workflow', table_name='scheduler_targets')
    op.drop_index('idx_scheduler_targets_group', table_name='scheduler_targets')
    op.drop_table('scheduler_targets')
    op.drop_table('branch_car_models')
    op.drop_table('sync_metadata')
    op.drop_index('idx_schedule_groups_workflow', table_name='schedule_groups')
    op.drop_table('schedule_groups')
    op.drop_table('report_jobs')
    op.drop_table('prompt_presets')
    op.drop_index('uq_monthly_sentiment_stats_composite', table_name='monthly_sentiment_stats')
    op.drop_index(op.f('ix_monthly_sentiment_stats_branch_id'), table_name='monthly_sentiment_stats')
    op.drop_table('monthly_sentiment_stats')
    op.drop_index('uq_monthly_rating_stats_composite', table_name='monthly_rating_stats')
    op.drop_index(op.f('ix_monthly_rating_stats_branch_id'), table_name='monthly_rating_stats')
    op.drop_table('monthly_rating_stats')
    op.drop_table('categories')
    op.drop_index('uq_car_models_master_model_name', table_name='car_models_master')
    op.drop_table('car_models_master')
    op.drop_table('car_models')
    op.drop_index(op.f('ix_branch_summaries_history_branch_id'), table_name='branch_summaries_history')
    op.drop_table('branch_summaries_history')
    op.drop_index(op.f('ix_branch_summaries_branch_id'), table_name='branch_summaries')
    op.drop_table('branch_summaries')
    op.drop_table('branch_scheduler_settings')
    op.drop_index('uq_branch_reviews_review_id', table_name='branch_reviews')
    op.drop_index(op.f('ix_branch_reviews_branch_id'), table_name='branch_reviews')
    op.drop_index('idx_branch_reviews_return_date', table_name='branch_reviews')
    op.drop_index('idx_branch_reviews_rental_date', table_name='branch_reviews')
    op.drop_table('branch_reviews')
    op.drop_index('uq_branch_reports_composite', table_name='branch_reports')
    op.drop_index(op.f('ix_branch_reports_branch_id'), table_name='branch_reports')
    op.drop_table('branch_reports')
    op.drop_index('uq_branch_keywords_composite', table_name='branch_keywords')
    op.drop_index(op.f('ix_branch_keywords_branch_id'), table_name='branch_keywords')
    op.drop_table('branch_keywords')
    op.drop_table('affiliates')
    # ### end Alembic commands ###
